"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { BookOpen, ShoppingBag } from "lucide-react";
import api from "@/lib/api";
import PublicShell from "@/components/public/public-shell";

type Book = { _id: string; title: string; author: string; category: string; coverImage?: string; description?: string; summary?: string; availableCopies: number; pages: number; language: string; amazonUrl?: string };
export default function BookDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [book, setBook] = useState<Book | null>(null); const [message, setMessage] = useState(""); const [review,setReview]=useState({rating:5,comment:""});
  useEffect(() => { api.get(`/books/${id}`).then((response) => setBook(response.data.book)); }, [id]);
  const reserve = async () => { try { await api.post("/loans/reserve", { book: id }); setMessage("Book reserved. View it in your account."); } catch (error: unknown) { const e = error as { response?: { status?: number; data?: { message?: string } } }; if (e.response?.status === 401) router.push("/login"); else setMessage(e.response?.data?.message || "Could not reserve book"); } };
  const submitReview=async()=>{try{await api.post("/reviews",{bookTitle:book?.title,rating:review.rating,comment:review.comment});setReview({rating:5,comment:""});setMessage("Review submitted for moderation.")}catch{router.push("/login")}};
  return <PublicShell><section className="mx-auto max-w-6xl px-6 py-14">{book && <><div className="grid gap-10 lg:grid-cols-[320px_1fr]"><div className="flex min-h-96 items-center justify-center overflow-hidden rounded-3xl bg-slate-100 shadow-sm">{book.coverImage ? <img src={book.coverImage} alt="" className="h-full w-full object-cover" /> : <BookOpen size={64} className="text-slate-300" />}</div><div><p className="font-bold uppercase tracking-wider text-blue-600">{book.category}</p><h1 className="mt-3 text-5xl font-black">{book.title}</h1><p className="mt-3 text-xl text-slate-500">by {book.author}</p><p className="mt-8 leading-8 text-slate-600">{book.description || book.summary || "Description coming soon."}</p><div className="mt-8 flex flex-wrap gap-3 text-sm text-slate-500"><span className="rounded-full bg-white px-4 py-2">{book.availableCopies} available</span><span className="rounded-full bg-white px-4 py-2">{book.pages || "—"} pages</span><span className="rounded-full bg-white px-4 py-2">{book.language || "English"}</span></div>{message && <p className="mt-6 rounded-xl bg-blue-50 p-4 text-blue-700">{message}</p>}<div className="mt-8 flex flex-wrap gap-4"><button onClick={reserve} disabled={book.availableCopies < 1} className="rounded-2xl bg-blue-600 px-7 py-4 font-bold text-white disabled:opacity-40">Reserve this book</button>{book.amazonUrl && <a href={book.amazonUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-2xl bg-orange-500 px-7 py-4 font-bold text-white"><ShoppingBag size={18} /> View on Amazon</a>}</div></div></div><section className="mt-14 rounded-3xl border bg-white p-6"><h2 className="text-2xl font-black">Share a review</h2><div className="mt-5 grid gap-4"><select value={review.rating} onChange={e=>setReview({...review,rating:Number(e.target.value)})} className="rounded-xl border p-3">{[5,4,3,2,1].map(v=><option key={v} value={v}>{v} stars</option>)}</select><textarea value={review.comment} onChange={e=>setReview({...review,comment:e.target.value})} placeholder="What did you think?" className="min-h-28 rounded-xl border p-3"/><button onClick={submitReview} disabled={!review.comment.trim()} className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white disabled:opacity-40">Submit review</button></div></section></>}</section></PublicShell>;
}
